// Minimal — generated by @web-kits/audio (do not edit)
// patch: Minimal
import type { SoundDefinition } from "@web-kits/audio";

export const tap: SoundDefinition = {"source":{"type":"sine","frequency":1200},"envelope":{"attack":0,"decay":0.012,"sustain":0,"release":0.004},"gain":0.08};
export const click: SoundDefinition = {"source":{"type":"sine","frequency":800},"envelope":{"attack":0,"decay":0.015,"sustain":0,"release":0.005},"gain":0.1};
export const toggleOn: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":880},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.08},{"source":{"type":"sine","frequency":1320},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"delay":0.03,"gain":0.07}]};
export const toggleOff: SoundDefinition = {"layers":[{"source":{"type":"sine","frequency":1320},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.08},{"source":{"type":"sine","frequency":880},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"delay":0.03,"gain":0.07}]};
export const hover: SoundDefinition = {"source":{"type":"sine","frequency":1300},"envelope":{"attack":0,"decay":0.01,"sustain":0,"release":0.004},"gain":0.04};
export const expand: SoundDefinition = {"source":{"type":"sine","frequency":{"start":800,"end":1000}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.06};
export const collapse: SoundDefinition = {"source":{"type":"sine","frequency":{"start":1000,"end":800}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.06};
export const send: SoundDefinition = {"source":{"type":"sine","frequency":{"start":600,"end":1000}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.08};
export const pop: SoundDefinition = {"source":{"type":"sine","frequency":{"start":400,"end":200}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.1};

